extends Node

const WONDER = {
	
	"Hanging Gardens" : {
		"image_name":"Hanging_Gardens",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_CULTURE,
		"description":"At the start of your turn, you may place 1 control token on a space of terrain difficulty 4 or less that is adjacent to a friendly city.",
		"cost":8,
		"additional_resource":gl.RESOURCE_DIAMOND},
	"Colosseum" : {
		"image_name":"Colosseum",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_CULTURE,
		"description":"At the start of your turn, you may reinforce 1 of your control tokens that is adjacent to a friendly city.",
		"cost":9,
		"additional_resource":gl.RESOURCE_OIL},
	"Stonehenge" : {
		"image_name":"Stonehenge",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_CULTURE,
		"description":"After you place a control token on a hill space, you may place a control token on 1 or more hill spaces (which can trigger this effect again).",
		"cost":7,
		"additional_resource":gl.RESOURCE_MERCURY},
	"Taj Mahal" : {
		"image_name":"Taj_Mahal",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_CULTURE,
		"description":"When you resolve a focus card, resolve it as though it is 1 slot farther to the right for each world wonder you control matching the focus card's type.",
		"cost":9,
		"additional_resource":gl.RESOURCE_DIAMOND},
	"Forbidden City" : {
		"image_name":"Forbidden_City",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_CULTURE,
		"description":"At the start of your turn, you may destroy 1 rival control token that is adjacent to a friendly space.",
		"cost":9,
		"additional_resource":gl.RESOURCE_OIL},
	"Chichen Itza" : {
		"image_name":"Chichen_Itza",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_CULTURE,
		"description":"When placing control tokens, you can place them on empty forest spaces that are not adjacent to a friendly city.",
		"cost":10,
		"additional_resource":gl.RESOURCE_MERCURY},
	"Sydney Opera House" : {
		"image_name":"Sydney_Opera_House",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_CULTURE,
		"description":"Rival control tokens contribute toward your cities' maturity.",
		"cost":10,
		"additional_resource":gl.RESOURCE_DIAMOND},
	"Eiffel Tower" : {
		"image_name":"Eiffel_Tower",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_CULTURE,
		"description":"At the start of your turn, you may choose 2 rival control tokens on the map belonging to the same player. That player replaces 1 of those tokens with 1 of your unused unreinforced control tokens.",
		"cost":12,
		"additional_resource":gl.RESOURCE_OIL},
	"Cristo Redentor" : {
		"image_name":"Cristo_Redentor",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_CULTURE,
		"description":"When you build or capture this wonder, choose a rival non-capital city (without an army in its space) within 3 spaces of this wonder. Replace that city with 1 of your unused cities.",
		"cost":11,
		"additional_resource":gl.RESOURCE_MERCURY},
	
	"Apadana" : {
		"image_name":"Apadana",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_ECONOMY,
		"description":"When you build or capture this wonder, choose an edge space on any tile. Explore from that space.\n\nThen if you placed a tile, place 1 control token on an empty space on that tile.",
		"cost":8,
		"additional_resource":gl.RESOURCE_MARBLE},
	"Colossus" : {
		"image_name":"Colossus",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_ECONOMY,
		"description":"When resolving your economy focus card, your caravans can move a total of 6 additional spaces, divided as you choose.",
		"cost":7,
		"additional_resource":gl.RESOURCE_OIL},
	"Great Lighthouse" : {
		"image_name":"Great_Lighthouse",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_ECONOMY,
		"description":"When building cities, you can build in empty spaces on the edge of the map as if they were within 2 spaces of a friendly space.",
		"cost":8,
		"additional_resource":gl.RESOURCE_MERCURY},
	"Kilwa Kisiwani" : {
		"image_name":"Kilwa_Kisiwani",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_ECONOMY,
		"description":"When you move a caravan to a city-state, place 1 additional trade token from the supply on any 1 of your focus cards.",
		"cost":9,
		"additional_resource":gl.RESOURCE_MARBLE},
	"Great Zimbabwe" : {
		"image_name":"Great_Zimbabwe",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_ECONOMY,
		"description":"You can place trade tokens on this card instead of on your focus cards, up to a limit of 4.\n\nAt the start of your turn, you may move trade tokens from this card to cards in your focus row.",
		"cost":9,
		"additional_resource":gl.RESOURCE_OIL},
	"Machu Pichu" : {
		"image_name":"Machu_Picchu",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_ECONOMY,
		"description":"When you resolve the card in the first or second slot of your focus row, resolve it as though it is 2 slots farther to the right.",
		"cost":10,
		"additional_resource":gl.RESOURCE_MERCURY},
	"Estadio do Maracana" : {
		"image_name":"Estadio_do_Maracana",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_ECONOMY,
		"description":"After you resolve a focus card other than your economy card, you may resolve and reset your economy card.",
		"cost":10,
		"additional_resource":gl.RESOURCE_MARBLE},
	"Orszaghaz" : {
		"image_name":"Orszaghaz",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_ECONOMY,
		"description":"After you move a caravan to a city-state, you may conquer it.",
		"cost":11,
		"additional_resource":gl.RESOURCE_OIL},
	"Big Ben" : {
		"image_name":"Big_Ben",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_ECONOMY,
		"description":"When attacking or defending, increase your combat value by 2 for each caravan adjacent to the defending space.",
		"cost":10,
		"additional_resource":gl.RESOURCE_MERCURY},
	
	"Terracota Army" : {
		"image_name":"Terracotta_Army",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_MILITARY,
		"description":"When attacking, increase your combat value by 2.",
		"cost":8,
		"additional_resource":gl.RESOURCE_MARBLE},
	"Petra" : {
		"image_name":"Petra",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_MILITARY,
		"description":"When defending, increase your combat value by 2.\n\nBarbarians cannot move into spaces containing your cities or reinforced control tokens.",
		"cost":7,
		"additional_resource":gl.RESOURCE_DIAMOND},
	"Jebel Barkal" : {
		"image_name":"Jebel_Barkal",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_MILITARY,
		"description":"When attacking or defending, you can spend resource tokens (not natural wonder tokens) to increase your combat value by 2 for each resource spent.",
		"cost":7,
		"additional_resource":gl.RESOURCE_MERCURY},
	"Alhambra" : {
		"image_name":"Alhambra",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_MILITARY,
		"description":"When attacking or defending, increase yout combat value by 2.",
		"cost":10,
		"additional_resource":gl.RESOURCE_MARBLE},
	"Venetian Arsenal" : {
		"image_name":"Venetian_Arsenal",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_MILITARY,
		"description":"Once per turn, after you resolve the card in your focus row, you may resolve it again, treating it as if it was in the first slot.",
		"cost":10,
		"additional_resource":gl.RESOURCE_DIAMOND},
	"Huey Teocalli" : {
		"image_name":"Huey_Teocalli",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_MILITARY,
		"description":"When defending, increase your combat value by 1 for each water space that is adjacent to the defending space.",
		"cost":9,
		"additional_resource":gl.RESOURCE_MERCURY},
	"Statue of Liberty" : {
		"image_name":"Statue_of_Liberty",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_MILITARY,
		"description":"Before you replace a rival city with 1 or your cities, replace all rival control tokens that are adjacent to that rival city with your unused, unreinforced control tokens.",
		"cost":12,
		"additional_resource":gl.RESOURCE_MARBLE},
	"Pentagon" : {
		"image_name":"Pentagon",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_MILITARY,
		"description":"When attacking, increase your combat value by 2.\n\nYour armies can move any number of spaces. (They must still obey all other movement rules.)",
		"cost":12,
		"additional_resource":gl.RESOURCE_DIAMOND},
	"Ruhr Valley" : {
		"image_name":"Ruhr_Valley",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_MILITARY,
		"description":"When defending, increase your combat value by 5.",
		"cost":11,
		"additional_resource":gl.RESOURCE_MERCURY},
	
	"Oracle" : {
		"image_name":"Oracle",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_SCIENCE,
		"description":"At the start of your turn, you may swap 2 adjacent cards in your focus row.",
		"cost":8,
		"additional_resource":gl.RESOURCE_MARBLE},
	"Great Library" : {
		"image_name":"Great_Library",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_SCIENCE,
		"description":"When your caravan moves to another player's city, you may gain a focus card of the same type and tech level as a card in that player's focus row, replacing your card of the same type.",
		"cost":8,
		"additional_resource":gl.RESOURCE_DIAMOND},
	"Pyramids" : {
		"image_name":"Pyramids",
		"era_type":gl.ERA_ANCIENT,
		"focus_type":gl.FOCUS_SCIENCE,
		"description":"When you build this wonder, choose up to 3 level-I cards in your focus row. Replace each with a level-II card of the same type.",
		"cost":9,
		"additional_resource":gl.RESOURCE_OIL},
	"Potala Palace" : {
		"image_name":"Potala_Palace",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_SCIENCE,
		"description":"You can have 4 diplomacy cards from each other player.\n\nWhen you build this wonder, you may take a total of 3 diplomacy cards of your choice from other players.",
		"cost":10,
		"additional_resource":gl.RESOURCE_MARBLE},
	"Porcelain Tower" : {
		"image_name":"Porcelain_Tower",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_SCIENCE,
		"description":"When you build this wonder, replace up to 2 cards in your focus row with cards of the next highest level of the same type.",
		"cost":9,
		"additional_resource":gl.RESOURCE_DIAMOND},
	"University of Sankore" : {
		"image_name":"University_of_Sankore",
		"era_type":gl.ERA_MEDIEVAL,
		"focus_type":gl.FOCUS_SCIENCE,
		"description":"At the end of your turn, if you replaced 1 or more of your focus cards this turn, you may sawp any 2 non-science cards in your row.",
		"cost":9,
		"additional_resource":gl.RESOURCE_OIL},
	"Oxford University" : {
		"image_name":"Oxford_University",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_SCIENCE,
		"description":"Whe you replace a focus card other than a science focus card, you do not have to replace it with a card of the same type.",
		"cost":10,
		"additional_resource":gl.RESOURCE_MARBLE},
	"Amundsen-Scott Research Station" : {
		"image_name":"Amundsen-Scott_Research_Station",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_SCIENCE,
		"description":"When you build this wonder, build a city on any legal space of the edge of the map and place this wonder in that city. Then place up to 2 control tokens in spaces adjacent to that city.",
		"cost":10,
		"additional_resource":gl.RESOURCE_DIAMOND},
	"Kremlin" : {
		"image_name":"Kremlin",
		"era_type":gl.ERA_MODERN,
		"focus_type":gl.FOCUS_SCIENCE,
		"description":"When attacking a rival space, increase your combat value by 4 if you have more reinforced control tokens on the map than the defending player.",
		"cost":11,
		"additional_resource":gl.RESOURCE_OIL},
	
}
